name: .NET CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: '8.0.x' # Change if using 7.x, 8.x, etc.

jobs:
  build-test-publish:
    name: Build, Test, and Publish
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore SalesTax.sln

      - name: Build solution
        run: dotnet build SalesTax.sln --configuration Release --no-restore

      - name: Run unit tests
        run: dotnet test SalesTaxTests/SalesTaxTests.csproj --no-build --verbosity normal

      - name: Publish app
        run: dotnet publish SalesTax/SalesTax.csproj --configuration Release --output ./publish

      - name: Upload published files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: SalesTaxApp
          path: ./publish

  deploy:
    name: Deploy from Artifact
    runs-on: windows-latest
    needs: build-test-publish

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: SalesTaxApp
          path: ./deploy

      - name: Deploy (placeholder)
        run: |
          echo "Deploying to target location..."
          # Replace this with your actual deploy logic (e.g., xcopy, robocopy, scp, Azure CLI)
          mkdir C:\inetpub\wwwroot\SalesTaxApp
          xcopy ".\deploy\*" "C:\inetpub\wwwroot\SalesTaxApp" /s /e /y
